[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
lexer = { path = "../lexer" }

lalrpop-util = { version = "0.22", default-features = false }


[build-dependencies]
lalrpop = { version = "0.22", default-features = false }
