[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
lexer = { path = "../lexer" }

lalrpop-util = { version = "0.22", features = ["lexer", "unicode"] }


[build-dependencies]
lalrpop = "0.22"
