grammar = { SOI ~ expr* ~ EOI }

// "1" is a bogus expression for now to play  with
simple_expr = { "1" | "(" ~ expr~ ")" }

expr = { simple_expr | if_expr }

if_expr = { "if" ~ simple_expr ~ "then" ~ if_body }

    if_body = { if_block_body | if_simple_body }

    if_block_body = { ":" ~ expr+ ~ ("end" | else) }

    if_simple_body = { (if_expr | simple_expr) ~ else? }

    else = { "else" ~ if_body }

// Tokens

WHITESPACE = _{ " " | "\t" | "\n" | "\r\n" }
