site_name: Interop Programming Language
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Introduction and Features: index.md
  - The Language:
      - Concepts: concepts.md
      - Types: types.md
      - Expressions: expressions.md
      - Statements: statements.md
      - Declarations: declarations.md
      - Comments: comments.md
